### ISSUE TITLE
Show the metadata of the validators

### ISSUE THREAD

**Issue by remagpie** [CodeChain-io/codechain-stakeholder-sdk-js#30]
The current implementation only shows the metadata of the candidates.
It'd be much better for the user experience if we show the metadata of the validators too.

**Comment by remagpie** [comment]
And the banned validators too if possible.

**Comment by foriequal0** [comment]
Banned account's metadata cannot be retrieved from current status. We can join validators and candidates to print validator's metadata since validator <= candidates.
